noun1 = input('Enter noun1: ')
adverb = input('Enter adverb: ')
noun2 = input('Enter noun2: ')
adj1 = input('Enter adjective1: ')
adj2 = input('Enter adjective2: ')
sport =input('Enter sport: ')
Professional_athlete = input('Enter player: ')
adj3 = input('Enter adjective3: ')

print('There once was this kid named ' + noun1)
print('He grew up ' + adverb + ' in the fast city of ' + noun2)
print(noun1 + ' was a ' + adj1 + ' kid just trying to make it in a ' + adj2 + ' world')
print('He loved ' + sport + ' and his favorite player was ' + Professional_athlete)
print(sport + ' was his only way out, so he thought. \n Little did he know was that he had so much more to offer')
print('The question is will the city of ' + noun2 + ' swallow him whole or \n will ' + noun1 + ' find his way in the ' + adj3 + ' city')
